name : PearlEnergyWeb

on:
    push:
        branches: [ master ]

jobs: 
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@2
            - uses: subotito/flutter-action@v1
            - uses: bluefireteam/flutter-gh-pages@v7